import { expect,test,type Page } from "@playwright/test";

const ok=(data:unknown)=>({status:"success",code:"OK",message:"ok",data});
const product={product_name:"테스트 상품",unit_price:12000,stock_limit:10,reserved_quantity:1,available_quantity:9,active:true,display_order:1};
async function readySession(page:Page){await page.addInitScript(()=>sessionStorage.setItem("live-purchase:waiting",JSON.stringify({enabled:true,status:"ready",ticket_id:"ticket-id",ticket_token:"ticket-token",position:0,retry_after_seconds:1})))}
async function mockProducts(page:Page){await page.route("**/api/products",r=>r.fulfill({json:ok({products:[product]})}))}
async function fillOrder(page:Page){await page.getByLabel("테스트 상품 수량 늘리기").click();await page.getByLabel("주문자명").fill("테스트 구매자");await page.getByLabel("전화번호").fill("000-0000-0000");await page.getByLabel("배송주소").fill("테스트 배송지 1");await page.getByLabel(/개인정보 수집/).check();await page.getByLabel(/구매·재고·계좌이체/).check();await page.getByRole("button",{name:"금액 확인하기"}).click()}
const quote={payment_amount:12000,quote_token:"server-quote-token",expires_at:"2099-01-01T00:00:00Z",lines:[{product_name:"테스트 상품",quantity:1,unit_price:12000,line_amount:12000,available_quantity:9,accepted:true},{product_name:"취소 상품",quantity:1,unit_price:5000,line_amount:0,available_quantity:0,accepted:false}]};

test("응답 CSP는 요청별 nonce를 사용하고 인라인 스크립트를 허용하지 않는다",async({request})=>{const response=await request.get("/");const csp=response.headers()["content-security-policy"]??"";const script=csp.split("; ").find(value=>value.startsWith("script-src"))??"";expect(script).toContain("'strict-dynamic'");expect(script).toMatch(/'nonce-[^']+'/);expect(script).not.toContain("'unsafe-inline'")});
test("대기 3회 후 ready가 되면 상품을 로드한다",async({page})=>{let checks=0;await page.route("**/waiting-room/tickets",r=>r.fulfill({json:ok({enabled:true,status:"waiting",ticket_id:"id",ticket_token:"token",position:4,retry_after_seconds:.01})}));await page.route("**/waiting-room/tickets/id",r=>r.fulfill({json:ok(++checks>=3?{enabled:true,status:"ready",position:0,retry_after_seconds:.01}:{enabled:true,status:"waiting",position:4-checks,retry_after_seconds:.01})}));await mockProducts(page);await page.goto("/");await page.getByRole("button",{name:"구매 대기줄 입장"}).click();await expect(page.getByText(/4번째/)).toBeVisible();await expect(page).toHaveURL(/\/purchase/,{timeout:7000});await expect(page.getByText("테스트 상품")).toBeVisible()});
test("review에서 partial 취소 줄·수취인·배송사·금액을 표시한다",async({page})=>{await readySession(page);await mockProducts(page);await page.route("http://localhost:8000/orders/quote",r=>r.fulfill({json:ok(quote)}));await page.goto("/purchase");await fillOrder(page);await expect(page).toHaveURL(/\/purchase\/review/);await expect(page.getByText(/제외 예정/)).toBeVisible();await expect(page.getByText("12,000원").first()).toBeVisible();await expect(page.getByText("테스트 구매자")).toBeVisible();await expect(page.getByText("CU(롯데택배)")).toBeVisible()});
test("만료된 견적은 확정할 수 없고 새 견적을 요구한다",async({page})=>{await readySession(page);await mockProducts(page);await page.route("http://localhost:8000/orders/quote",r=>r.fulfill({json:ok({...quote,expires_at:"2000-01-01T00:00:00Z"})}));let orders=0;await page.route("http://localhost:8000/orders",r=>{orders++;return r.abort()});await page.goto("/purchase");await fillOrder(page);await expect(page.getByText(/견적 유효시간이 지났습니다/)).toBeVisible();await expect(page.getByRole("button",{name:"새 견적 받기"})).toBeVisible();expect(orders).toBe(0)});
test("Turnstile mock 후 견적 토큰으로 주문을 한 번만 생성하고 보관정보를 복사한다",async({page,context})=>{await context.grantPermissions(["clipboard-read","clipboard-write"]);await readySession(page);await mockProducts(page);await page.route("http://localhost:8000/orders/quote",r=>r.fulfill({json:ok(quote)}));let orders=0;let submitted:Record<string,unknown>={};await page.route("http://localhost:8000/orders",async r=>{orders++;submitted=await r.request().postDataJSON();return r.fulfill({json:ok({order_reference:"ORDER-E2E",order_token:"LOOKUP-E2E",payment_amount:12000,accepted_count:1,cancelled_count:1})})});await page.goto("/purchase");await fillOrder(page);await page.getByRole("button",{name:"로컬 검증 토큰 사용"}).click();await page.getByRole("button",{name:"구매내역 확정"}).dblclick();await expect(page).toHaveURL(/complete/);expect(orders).toBe(1);expect(submitted.quote_token).toBe("server-quote-token");expect(submitted).toHaveProperty("push_token");expect(await page.evaluate(()=>sessionStorage.getItem("live-purchase:waiting"))).toBeNull();await page.getByRole("button",{name:"주문번호 복사"}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe("ORDER-E2E")});
test("409이면 견적 토큰을 폐기한다",async({page})=>{await readySession(page);await mockProducts(page);await page.route("http://localhost:8000/orders/quote",r=>r.fulfill({json:ok(quote)}));await page.route("http://localhost:8000/orders",r=>r.fulfill({status:409,json:{status:"error",code:"CHANGED",message:"changed"}}));await page.goto("/purchase");await fillOrder(page);await page.getByRole("button",{name:"로컬 검증 토큰 사용"}).click();await page.getByRole("button",{name:"구매내역 확정"}).click();await expect(page.getByRole("alert").filter({hasText:"가격·재고"})).toBeVisible();await expect(page.getByRole("button",{name:"새 견적 받기"})).toBeVisible()});
test("주문 timeout은 자동 재전송하지 않는다",async({page})=>{await readySession(page);await mockProducts(page);await page.route("http://localhost:8000/orders/quote",r=>r.fulfill({json:ok(quote)}));let calls=0;await page.route("http://localhost:8000/orders",r=>{calls++;return r.abort("timedout")});await page.goto("/purchase");await fillOrder(page);await page.getByRole("button",{name:"로컬 검증 토큰 사용"}).click();await page.getByRole("button",{name:"구매내역 확정"}).click();await expect(page.getByText(/자동으로 다시 제출하지/)).toBeVisible();expect(calls).toBe(1)});
test("입금부족에서 추가 입금 안내 후 결제완료를 표시한다",async({page})=>{let calls=0;await page.route(/\/orders\/REF\/status$/,r=>r.fulfill({json:ok({order_reference:"REF",status:++calls>1?"결제완료":"입금부족",created_at:"2026-01-01T00:00:00Z",buyer_name:"테***",phone:"000-****-0000",address:"테스트 **",expected_amount:12000,paid_amount:calls>1?12000:10000,difference:calls>1?0:2000,courier:{provider:"cu_lotte",display_name:"CU(롯데택배)",tracking_url:"https://www.lotteglogis.com/track"},items:[]})}));await page.goto("/orders/lookup");await page.getByLabel("주문번호").fill("REF");await page.getByLabel("비밀 조회키").fill("TOKEN");await page.getByRole("button",{name:"주문 상태 확인"}).click();await expect(page.getByText(/부족합니다/)).toBeVisible();await page.getByRole("button",{name:"주문 상태 확인"}).click();await expect(page.getByText(/완료되었습니다/)).toBeVisible()});
test("잘못된 조회키 404는 일반 메시지를 표시한다",async({page})=>{await page.route(/\/orders\/BAD\/status$/,r=>r.fulfill({status:404,json:{status:"error",code:"NOT_FOUND",message:"secret invalid"}}));await page.goto("/orders/lookup");await page.getByLabel("주문번호").fill("BAD");await page.getByLabel("비밀 조회키").fill("WRONG");await page.getByRole("button",{name:"주문 상태 확인"}).click();await expect(page.getByText(/주문번호와 조회키를 다시 확인/)).toBeVisible();await expect(page.getByText(/secret invalid/)).toHaveCount(0)});
test("429 Retry-After를 표시한다",async({page})=>{await page.route(/\/orders\/RATE\/status$/,r=>r.fulfill({status:429,headers:{"Retry-After":"9","Access-Control-Expose-Headers":"Retry-After","Content-Type":"application/json"},body:JSON.stringify({status:"error",code:"RATE",message:"요청이 많습니다."})}));await page.goto("/orders/lookup");await page.getByLabel("주문번호").fill("RATE");await page.getByLabel("비밀 조회키").fill("TOKEN");await page.getByRole("button",{name:"주문 상태 확인"}).click();await expect(page.getByText(/9초 후/)).toBeVisible()});
test("expired 대기표는 명시적 재발급을 요구한다",async({page})=>{await page.route("http://localhost:8000/waiting-room/tickets",r=>r.fulfill({json:ok({enabled:true,status:"waiting",ticket_id:"id",ticket_token:"token",position:1,retry_after_seconds:.01})}));await page.route(/waiting-room\/tickets\/id$/,r=>r.fulfill({json:ok({enabled:true,status:"expired",position:0,retry_after_seconds:.01})}));await page.goto("/");await page.getByRole("button",{name:"구매 대기줄 입장"}).click();await expect(page.getByRole("button",{name:"새 대기표 받기"})).toBeVisible({timeout:3000})});
test("관리자 상품 수정에서 서버 409를 표시한다",async({page})=>{await page.route("http://localhost:8000/admin/api/products",async r=>{if(r.request().method()==="GET")return r.fulfill({json:ok({products:[{...product,reserved_quantity:3,available_quantity:7}]})});return r.fulfill({status:409,json:{status:"error",code:"STOCK",message:"conflict"}})});await page.goto("/admin/products");await page.getByLabel("API 키").fill("test-admin-key");await page.getByRole("button",{name:/키 확인/}).click();await page.getByRole("row",{name:/테스트 상품/}).click();await page.getByLabel("총 재고").fill("2");await page.getByRole("button",{name:/저장 전/}).click();await page.getByRole("button",{name:"변경 내용 저장"}).click();await expect(page.getByText(/예약수량보다 총 재고/)).toBeVisible()});
